name: second_hand_electronics_marketplace
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  country_picker: ^2.0.27
  country_code_picker: ^3.4.1
  device_preview: ^1.3.1
  equatable: ^2.0.8
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_face_detection: ^0.13.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.3
  go_router: ^17.0.1
  flutter_bloc: ^9.1.1
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  google_maps_flutter: ^2.14.0
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  camera: ^0.11.3
  flutter_image_compress: ^2.4.0
  flutter_easyloading: ^3.0.5
  image_picker: ^1.2.1
<<<<<<< HEAD
  cupertino_icons: ^1.0.8
  google_fonts: ^6.0.0
  audioplayers: ^5.2.1
  audio_waveforms: ^2.0.2
  http: ^1.0.0
  cached_network_image: ^3.2.3
  just_audio: ^0.9.39  
  dio: ^5.2.1
  dotted_border: ^2.1.0
  record: ^6.1.2
  flutter_sound: ^9.3.18+1
  flutter_cache_manager: ^3.4.1
  stop_watch_timer: ^3.1.0
=======
>>>>>>> 99c4b78366eb600f65ee24d30c1a01cfa052635d

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/svgs/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
